### ISSUE TITLE
Separate switches?

### ISSUE THREAD

**Issue by mbriney** [joshualyon/STWinkRelay#5]
Is it possible to have two separate switches in SmartThings instead of just a single master?  I know you can go into the switch and then independently control each of the virtual switches.  But when you hook SmartThings into Google Home or Homebridge (Homekit) the device only shows up as a single switch and doesn't allow independent control of each of the buttons.

**Comment by joshualyon** [comment]
Each of the child switches are individual devices. 

How they are exposed in other integrations depends on the integration itself. For example, the individual child switches are exposed to integrations like SharpTools, WebCoRE, etc.

You may be able to modify the parent device handler so each of the children are no longer grouped together with the parent to force them to be individually exposed to Google Home (or other integrations), but this isn't something I would do by default in the released code as it's really the responsibility of the integration to expose the child devices. 

Unfortunately, the _new_ SmartThings-Google Home integration doesn't currently support child devices even though the previous version does. See the 'Note' section in the following post announcing the new Google Home integration:

https://community.smartthings.com/t/updates-to-google-integration/192849?u=joshua_lyon

**Comment by joshualyon** [comment]
Replying from my phone, so excuse my brevity, but if I remember correctly, you can change `isComponent` to false during the child device creation and the individual switches will get created as top level devices rather than components of the parent device. 

https://github.com/joshualyon/STWinkRelay/blob/bd1f244f3a40919e293c2a5b212cdcfa9c5c5743/devicetypes/joshualyon/wink-relay.src/wink-relay.groovy#L128
